Repository Astrotomic/opendor.me, pull requests merged in 2021-04, with the labels that each got.

#49 release
  app/Http/Controllers/Auth/GithubController.php
  app/Http/Policies/PermissionsPolicy.php
  app/Models/User.php
  app/Nova/Actions/AnonymizeUser.php
  app/Nova/User.php
  app/Providers/AppServiceProvider.php
Labels: release

#51 release
  app/Models/Repository.php
  composer.json
Labels: release

#54 Adds "Why are contributions missing?" FAQ content.
  content/faqs/why-are-contributions-missing.md
Labels: documentation

#57 release
  app/Enums/Language.php
  app/Enums/License.php
  app/Jobs/GithubJob.php
  app/Jobs/LoadRepositoryContributors.php
  app/Models/Organization.php
  app/Models/Repository.php
  app/Models/User.php
  app/Nova/FAQ.php
  composer.json
  config/horizon.php
  content/faqs/why-are-contributions-missing.md
  content/faqs/why-is-my-organization-not-indexed.md
  tailwind.config.js
Labels: release

#58 release
  app/Enums/Language.php
  app/Enums/License.php
  tailwind.config.js
Labels: release

#62 release
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  app/Console/Commands/GithubRepositoryContributors.php
  app/Http/Controllers/Auth/GithubController.php
  app/Jobs/AddRepositoryContributor.php
  app/Jobs/GithubJob.php
  app/Jobs/Job.php
  app/Jobs/LoadOrganizationRepositories.php
  app/Jobs/LoadRepositoryContributors.php
  app/Jobs/LoadUserRepositories.php
  app/Jobs/SyncUserOrganizations.php
  app/Jobs/UpdateOrganizationDetails.php
  app/Jobs/UpdateRepositoryDetails.php
  app/Jobs/UpdateUserDetails.php
  app/Models/Repository.php
  app/Models/User.php
  app/Nova/Actions/LoadContributors.php
  app/Observers/RepositoryObserver.php
  config/horizon.php
  database/migrations/2021_04_18_160520_create_job_batches_table.php
  database/migrations/2021_04_18_162217_add_emails_to_users_table.php
  resources/views/errors/404.blade.php
  tests/Utils/UserAssertions.php
Labels: release

#65 release
  composer.json
  package.json
  resources/views/components/card/repository.blade.php
  resources/views/components/card/user.blade.php
  resources/views/components/layout/app.blade.php
  resources/views/components/layout/error.blade.php
  resources/views/components/logo.blade.php
  resources/views/components/profile/aside.blade.php
  resources/views/components/profile/verified.blade.php
  resources/views/components/repository/stars.blade.php
  resources/views/components/web/footer.blade.php
  resources/views/components/web/github-sponsors.blade.php
  resources/views/components/web/header.blade.php
  resources/views/components/web/home/user-autocomplete.blade.php
  resources/views/errors/404.blade.php
  resources/views/errors/oauth_state.blade.php
  resources/views/web/profile/user.blade.php
Labels: release

#67 release
  app/Http/Controllers/FallbackController.php
  content/faqs/what-is-the-point-of-opendorme.md
  resources/views/components/web/faqs.blade.php
  resources/views/components/web/footer.blade.php
Labels: release

#72 replace Fuse.js with Algolia for home user search
  .env.example
  algolia/scout-local-users.php
  algolia/scout-prod-users.php
  app/Console/Kernel.php
  app/Http/Policies/ContentSecurityPolicy.php
  app/Models/User.php
  composer.json
  config/horizon.php
  config/scout.php
  package.json
  resources/js/alpine/fuse.js
  resources/js/app.js
  resources/views/components/layout/html.blade.php
  resources/views/components/web/home/user-autocomplete.blade.php
Labels: enhancement

#73 release
  .env.example
  algolia/scout-local-users.php
  algolia/scout-prod-users.php
  app/Console/Kernel.php
  app/Http/Controllers/Auth/GithubController.php
  app/Http/Policies/ContentSecurityPolicy.php
  app/Models/User.php
  app/View/Components/Web/Home/Stats.php
  composer.json
  config/horizon.php
  config/scout.php
  package.json
  resources/js/alpine/fuse.js
  resources/js/app.js
  resources/js/serviceworker.js
  resources/views/components/layout/html.blade.php
  resources/views/components/repository/language.blade.php
  resources/views/components/web/home/user-autocomplete.blade.php
  tailwind.config.js
Labels: release

#74 release
  app/Http/Controllers/Auth/GithubController.php
  resources/views/components/web/home/user-autocomplete.blade.php
Labels: release

#75 release
  resources/images/sponsors/algolia.svg
  resources/images/sponsors/enlightn.png
  resources/images/sponsors/pingping.svg
  resources/images/sponsors/plausible.png
  resources/views/components/web/home/user-autocomplete.blade.php
  resources/views/components/web/sponsors.blade.php
  tailwind.config.js
Labels: release

#76 release
  app/Nova/Resource.php
  config/horizon.php
  routes/api.php
Labels: release

#81 release
  app/Http/Controllers/Web/ProfileController.php
  app/Jobs/LoadOrganizationRepositories.php
  app/Jobs/LoadUserRepositories.php
  app/Models/Repository.php
  app/View/Components/Web/Home/RandomContributors.php
  app/View/Components/Web/Home/RandomOrganizations.php
  app/View/Components/Web/Home/RandomRepositories.php
  app/View/Components/Web/Home/Stats.php
Labels: release

#85 Advanced user search
  algolia/scout-local-users.php
  algolia/scout-prod-users.php
  app/Http/Policies/ContentSecurityPolicy.php
  app/Models/User.php
  package.json
  resources/js/app.js
  resources/views/components/card/user.blade.php
  resources/views/components/web/header.blade.php
  resources/views/components/web/home/user-autocomplete.blade.php
  resources/views/web/search/user.blade.php
  routes/web.php
  tailwind.config.js
Labels: enhancement

#86 release
  algolia/scout-local-users.php
  algolia/scout-prod-users.php
  app/Http/Policies/ContentSecurityPolicy.php
  app/Jobs/GithubJob.php
  app/Models/User.php
  package.json
  resources/js/app.js
  resources/views/components/card/user.blade.php
  resources/views/components/web/header.blade.php
  resources/views/components/web/home/user-autocomplete.blade.php
  resources/views/web/search/user.blade.php
  routes/web.php
  tailwind.config.js
Labels: release

#87 release
  app/Eloquent/Scopes/OrderByScope.php
  app/Models/Organization.php
  app/Models/Repository.php
  app/Models/User.php
  app/Nova/Metrics/RepositoriesPerLanguage.php
  app/Nova/Metrics/RepositoriesPerLicense.php
  app/Observers/OrganizationObserver.php
  app/Observers/UserObserver.php
  app/Providers/AppServiceProvider.php
  app/View/Components/Web/Home/RandomContributors.php
  app/View/Components/Web/Home/RandomOrganizations.php
  app/View/Components/Web/Home/RandomRepositories.php
Labels: release

#93 release
  app/Console/Commands/GithubRepositoryContributors.php
  app/Console/Kernel.php
  app/Eloquent/Orbit.php
  app/Jobs/LoadRepositoryContributors.php
  app/Models/FAQ.php
  app/Models/Sponsor.php
  app/Providers/AppServiceProvider.php
  app/View/Components/Web/Sponsors.php
  composer.json
  config/schedule-monitor.php
  content/sponsors/algolia.yml
  content/sponsors/enlightn.yml
  content/sponsors/pingping.yml
  content/sponsors/plausible.yml
  resources/views/components/web/sponsors.blade.php
Labels: release

#94 release
  app/Enums/License.php
Labels: release
