Repository Astrotomic/opendor.me, pull requests merged in 2022-05, with the labels that each got.

#160 release
  .php-cs-fixer.dist.php
  .php-cs-rules.laravel.php
  app/Console/Commands/GithubLanguages.php
  app/Console/Commands/GithubOrganizationDetails.php
  app/Console/Commands/GithubOrganizationRepositories.php
  app/Console/Commands/GithubRepositoryDetails.php
  app/Console/Commands/GithubUserContributions.php
  app/Console/Commands/GithubUserDetails.php
  app/Console/Commands/GithubUserRepositories.php
  app/Eloquent/Orbit.php
  app/Http/Controllers/Admin/OrganizationCrudController.php
  app/Http/Controllers/Admin/RepositoryCrudController.php
  app/Http/Controllers/Admin/UserCrudController.php
  app/Http/Kernel.php
  app/Http/Policies/PermissionsPolicy.php
  app/Jobs/GithubJob.php
  app/Jobs/Job.php
  app/Jobs/LoadOrganizationRepositories.php
  app/Jobs/LoadUserRepositories.php
  app/Jobs/SyncUserContributions.php
  app/Jobs/SyncUserOrganizations.php
  app/Jobs/UpdateOrganizationDetails.php
  app/Jobs/UpdateRepositoryDetails.php
  app/Jobs/UpdateUserDetails.php
  app/Models/Organization.php
  app/Models/Repository.php
  app/Models/User.php
  app/Providers/EventServiceProvider.php
  app/Providers/HorizonServiceProvider.php
  app/View/Components/Layout/App.php
  app/View/Components/Layout/Html.php
  app/View/Components/Layout/Web.php
  app/View/Components/Numeral.php
  app/View/Components/Web/Faqs.php
  app/View/Components/Web/GithubSponsors.php
  app/View/Components/Web/Home/RandomContributors.php
  app/View/Components/Web/Home/RandomOrganizations.php
  app/View/Components/Web/Home/RandomRepositories.php
  app/View/Components/Web/Profile/UserSummary.php
  composer.json
  config/backpack/crud.php
  config/horizon.php
  config/ide-helper.php
  content/sponsors/ecologi.yml
  content/sponsors/hetzner.yml
  database/migrations/2021_04_01_135908_create_permission_tables.php
  database/seeders/DatabaseSeeder.php
  resources/images/sponsors/ecologi.svg
  resources/images/sponsors/hetzner.svg
  routes/channels.php
  tests/Feature/Jobs/GithubJobTest.php
  tests/Pest.php
Labels: release

#162 Laravel 9.x Shift
  app/Http/Kernel.php
  app/Http/Middleware/TrimStrings.php
  app/Http/Middleware/TrustProxies.php
  app/Providers/EventServiceProvider.php
  app/Providers/RouteServiceProvider.php
  composer.json
  config/app.php
  config/auth.php
  config/broadcasting.php
  config/cache.php
  config/database.php
  config/filesystems.php
  config/hashing.php
  config/logging.php
  config/mail.php
  config/queue.php
  config/services.php
  config/session.php
  database/factories/RepositoryFactory.php
  database/factories/UserFactory.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2018_01_01_000000_create_action_events_table.php
  database/migrations/2019_05_10_000000_add_fields_to_action_events_table.php
  database/migrations/2019_08_19_000000_create_failed_jobs_table.php
  database/migrations/2021_03_15_003309_create_organizations_table.php
  database/migrations/2021_03_15_003733_create_organization_user_table.php
  database/migrations/2021_03_15_113207_create_repositories_table.php
  database/migrations/2021_03_15_122407_create_repository_user_table.php
  database/migrations/2021_03_27_164922_add_profile.php
  database/migrations/2021_03_28_204140_create_schedule_monitor_tables.php
  database/migrations/2021_03_29_194653_create_faqs_table.php
  database/migrations/2021_04_01_135908_create_permission_tables.php
  database/migrations/2021_04_11_181126_drop_faqs_table.php
  database/migrations/2021_04_18_160520_create_job_batches_table.php
  database/migrations/2021_04_18_162217_add_emails_to_users_table.php
  database/migrations/2021_07_09_133913_add_referrer_to_users_table.php
  database/migrations/2021_07_09_153205_purge_spatie_permissions.php
  database/migrations/2021_08_23_083951_add_registered_at_to_users_table.php
  database/migrations/2021_08_23_104301_purge_filament.php
  database/migrations/2021_08_23_105107_purge_nova.php
  database/migrations/2021_08_24_122207_add_randomness_to_tables.php
  lang/.gitignore
  lang/en.json
  lang/en/auth.php
  lang/en/pagination.php
  lang/en/passwords.php
  lang/en/validation.php
  public/index.php
  routes/backpack/custom.php
  server.php
  stubs/migration.create.stub
  stubs/migration.stub
  stubs/migration.update.stub
Labels: enhancement

#164 Laravel 9.x Shift
  app/Http/Kernel.php
  app/Http/Middleware/TrimStrings.php
  app/Http/Middleware/TrustProxies.php
  app/Providers/AppServiceProvider.php
  app/Providers/EventServiceProvider.php
  app/Providers/RouteServiceProvider.php
  composer.json
  config/app.php
  config/auth.php
  config/broadcasting.php
  config/cache.php
  config/database.php
  config/filesystems.php
  config/hashing.php
  config/logging.php
  config/mail.php
  config/services.php
  config/session.php
  content/sponsors/laravelshift.yml
  database/factories/RepositoryFactory.php
  database/factories/UserFactory.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2018_01_01_000000_create_action_events_table.php
  database/migrations/2019_05_10_000000_add_fields_to_action_events_table.php
  database/migrations/2019_08_19_000000_create_failed_jobs_table.php
  database/migrations/2021_03_15_003309_create_organizations_table.php
  database/migrations/2021_03_15_003733_create_organization_user_table.php
  database/migrations/2021_03_15_113207_create_repositories_table.php
  database/migrations/2021_03_15_122407_create_repository_user_table.php
  database/migrations/2021_03_27_164922_add_profile.php
  database/migrations/2021_03_28_204140_create_schedule_monitor_tables.php
  database/migrations/2021_03_29_194653_create_faqs_table.php
  database/migrations/2021_04_01_135908_create_permission_tables.php
  database/migrations/2021_04_11_181126_drop_faqs_table.php
  database/migrations/2021_04_18_160520_create_job_batches_table.php
  database/migrations/2021_04_18_162217_add_emails_to_users_table.php
  database/migrations/2021_07_09_133913_add_referrer_to_users_table.php
  database/migrations/2021_07_09_153205_purge_spatie_permissions.php
  database/migrations/2021_08_23_083951_add_registered_at_to_users_table.php
  database/migrations/2021_08_23_104301_purge_filament.php
  database/migrations/2021_08_23_105107_purge_nova.php
  database/migrations/2021_08_24_122207_add_randomness_to_tables.php
  lang/.gitignore
  lang/en.json
  lang/en/auth.php
  lang/en/pagination.php
  lang/en/passwords.php
  lang/en/validation.php
  public/index.php
  resources/images/sponsors/laravelshift.svg
  routes/backpack/custom.php
  server.php
  stubs/migration.create.stub
  stubs/migration.stub
  stubs/migration.update.stub
Labels: enhancement

#163 drop everything email related for increased privacy
  app/Eloquent/QueryBuilders/UserQueryBuilder.php
  app/Http/Controllers/Admin/UserCrudController.php
  app/Http/Controllers/Auth/GithubController.php
  app/Jobs/UpdateUserDetails.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  database/factories/UserFactory.php
  database/migrations/2022_05_05_142019_drop_email_from_users_table.php
  tests/Feature/Models/UserTest.php
  tests/Utils/UserAssertions.php
Labels: enhancement

#166 release
  app/Eloquent/QueryBuilders/UserQueryBuilder.php
  app/Http/Controllers/Admin/UserCrudController.php
  app/Http/Controllers/Auth/GithubController.php
  app/Jobs/UpdateUserDetails.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  database/factories/UserFactory.php
  database/migrations/2022_05_05_142019_drop_email_from_users_table.php
  tests/Feature/Models/UserTest.php
  tests/Utils/UserAssertions.php
Labels: release

#168 release
  app/Jobs/UpdateUserDetails.php
  tests/fixtures/user/6187884.json
Labels: bug, release

#170 release
  app/Jobs/LoadOrganizationRepositories.php
  app/Jobs/LoadUserRepositories.php
  app/Jobs/SyncUserOrganizations.php
  tests/fixtures/organizations/2034458.json
  tests/fixtures/organizations/2034458/repos.json
  tests/fixtures/organizations/22500831.json
  tests/fixtures/organizations/22500831/repos.json
  tests/fixtures/organizations/27285508.json
  tests/fixtures/organizations/27285508/repos.json
  tests/fixtures/user/6187884.json
  tests/fixtures/user/6187884/repos.json
  tests/fixtures/user/973269.json
  tests/fixtures/user/973269/repos.json
Labels: bug, release

#171 release
  app/Jobs/UpdateOrganizationDetails.php
  app/Jobs/UpdateRepositoryDetails.php
Labels: bug, release

#172 switch from backpack to filament
  app/Backpack/CrudPanel.php
  app/Filament/Resource.php
  app/Filament/Resources/OrganizationResource.php
  app/Filament/Resources/OrganizationResource/Pages/EditOrganization.php
  app/Filament/Resources/OrganizationResource/Pages/ListOrganizations.php
  app/Filament/Resources/RepositoryResource.php
  app/Filament/Resources/RepositoryResource/Pages/CreateRepository.php
  app/Filament/Resources/RepositoryResource/Pages/EditRepository.php
  app/Filament/Resources/RepositoryResource/Pages/ListRepositories.php
  app/Filament/Resources/UserResource.php
  app/Filament/Resources/UserResource/Pages/EditUser.php
  app/Filament/Resources/UserResource/Pages/ListUsers.php
  app/Filament/Widgets/StatsOverview.php
  app/Http/Controllers/Admin/OrganizationCrudController.php
  app/Http/Controllers/Admin/RepositoryCrudController.php
  app/Http/Controllers/Admin/UserCrudController.php
  app/Http/Controllers/RobotsTxtController.php
  app/Http/Middleware/AuthenticateFilament.php
  app/Http/Middleware/CheckIfAdmin.php
  app/Http/Requests/OrganizationRequest.php
  app/Http/Requests/RepositoryRequest.php
  app/Http/Requests/UserRequest.php
  app/Models/Organization.php
  app/Models/Repository.php
  app/Models/User.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  composer.json
  config/backpack/base.php
  config/backpack/crud.php
  config/filament.php
  resources/views/components/user-dropdown.blade.php
  resources/views/errors/layout.blade.php
  resources/views/vendor/backpack/base/inc/menu_user_dropdown.blade.php
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
  resources/views/vendor/backpack/crud/columns/select_from_array.blade.php
  routes/backpack/custom.php
  webpack.mix.js
Labels: bug, enhancement
